export const ADD_PERSON = "ADD_PERSON";
export const SET_PERSONS = "SET_PERSONS";
export const SET_CARGOS = "SET_CARGOS";
export const FETCH_PERSONS_FAILED = "FETCH_PERSONS_FAILED";
export const FETCH_CARGOS_FAILED = "FETCH_CARGOS_FAILED";