export const ADD_PERSON = "ADD_PERSON";
export const SET_PERSONS = "SET_PERSONS";
export const SET_CARGOS = "SET_CARGOS";
export const FETCH_PERSONS_FAILED = "FETCH_PERSONS_FAILED";
export const FETCH_CARGOS_FAILED = "FETCH_CARGOS_FAILED";


// Auth

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";