
// SITE
export const SET_DATASITE = "SET_DATASITE";
export const SET_OPINION = "SET_OPINION";
export const FETCH_DATASITE_FAILED = "FETCH_DATASITE_FAILED";

// Auth

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const CLEAR_DATA = "CLEAR_DATA";
export const AUTH_FAIL = "AUTH_FAIL";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const INPUT_CHANGED_HANDLER = "INPUT_CHANGED_HANDLER";
export const SWITCH_AUTH_MODE_HANDLER = "SWITCH_AUTH_MODE_HANDLER";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

//Opinion
export const OPINION_START = "OPINION_START";
export const EDIT_OPINION = "EDIT_OPINION";
export const FETCH_OPINION_FAILED = "FETCH_OPINION_FAILED";
export const SEND_OPINION_FAILED = "SEND_OPINION_FAILED";
export const INPUT_OPINION_CHANGED_HANDLER = "INPUT_OPINION_CHANGED_HANDLER";
